#!/sbin/busybox sh

if [ "$2" == "/proc/sys/vm/drop_caches" ]; then
  sync
fi

if [ -f $2 ];then
	FILEVAR=$(basename $2)

	if [ -z $3 ]; then
		evalcmd='eval echo \$$FILEVAR'
		if [ "a`eval $evalcmd`" == "a" ]; then
			eval $FILEVAR=`cat $2`
			echo $FILEVAR=`cat $2` >> $DEFAULT_PROFILE
		fi
	else
		echo $3 > $2
		eval $FILEVAR=`cat $2`
	fi

if [[ "$2" == "/proc/sys/vm/drop_caches" ]] && [[ "$3" == "0" ]]
  sync
  echo "0" > $2
fi

	eval echo \$$FILEVAR
fi
