#!/sbin/busybox sh

if [ -f $2 ];then
	FILEVAR=$(basename $2)

grep -q "scoobyds_predef=.*" $DEFAULT_PROFILE && awk '!/scoobyds_predef=.*/' $DEFAULT_PROFILE > /res/temp && mv /res/temp $DEFAULT_PROFILE


	if [ -z $3 ]; then
		evalcmd='eval echo \$$FILEVAR'
		if [ "a`eval $evalcmd`" == "a" ]; then
			eval $FILEVAR=`cat $2`
			echo $FILEVAR=`cat $2` >> $DEFAULT_PROFILE
		fi
	else
		echo $3 > $2
		eval $FILEVAR=`cat $2`
	fi

	eval echo \$$FILEVAR
fi
